qoutes missing does not compile
merge this and it should compile at least for this part

`cc/../komodo_defs.h:398:90: warning: missing terminating " character
         {"decker_DEV, "02fca8ee50e49f480de275745618db7b0b3680b0bdcce7dcae7d2e0fd5c3345744" }
                                                                                          ^
cc/../komodo_defs.h:398:90: error: missing terminating " character
         {"decker_DEV, "02fca8ee50e49f480de275745618db7b0b3680b0bdcce7dcae7d2e0fd5c3345744" }
                                                                                          ^~~
cc/../komodo_defs.h:335:22: error: expected ‘}’ before numeric constant
         {"alien_AR, "024f20c096b085308e21893383f44b4faf1cdedea9ad53cc7d7e7fbfa0c30c1e71" },
`